galaxy_info:
  author: Diksha
  description: Ansible role to deploy a FastAPI + Redis application on Kubernetes
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: all
  galaxy_tags:
    - kubernetes
    - ansible
    - k8s
    - deployment

dependencies: []
