---
- import_tasks: namespace.yml
  tags:
    - namespace

- import_tasks: deploy.yml
  tags:
    - deploy

- import_tasks: scale.yml
  tags:
    - scale

- import_tasks: validate.yml
  tags:
    - validate
