---
- name: Compute ConfigMap Checksum
  set_fact:
    configmap_hash: "{{ lookup('template', 'configmap.yml.j2') | hash('sha256') }}"
  tags:
    - configmap

- name: Deploy ConfigMap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'configmap.yml.j2') }}"
  tags:
    - configmap
