---
- block:

    - name: Create Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'deployment.yml.j2') }}"
      register: deploy_result
      retries: 3
      delay: 10
      until: deploy_result is not failed

    - name: Create Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'service.yml.j2') }}"

    - name: Wait For Rollout To Complete
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ namespace_name }}"
      register: rollout_info
      retries: 12
      delay: 12
      until: >
        rollout_info.resources | length > 0 and
        rollout_info.resources[0].status.updatedReplicas | default(0) == rollout_info.resources[0].status.replicas | default(1) and
        rollout_info.resources[0].status.availableReplicas | default(0) == rollout_info.resources[0].status.replicas | default(1)
      when: deploy_result.changed

    - name: Print Rollout Status
      debug:
        msg: >
          Rollout status — desired: {{ rollout_info.resources[0].status.replicas | default('N/A') }},
          updated: {{ rollout_info.resources[0].status.updatedReplicas | default('N/A') }},
          available: {{ rollout_info.resources[0].status.availableReplicas | default('N/A') }}
      when: deploy_result.changed

    - name: Mark deployment success
      set_fact:
        deployment_status: "SUCCESS"

  rescue:

    - name: Mark deployment failed
      set_fact:
        deployment_status: "FAILED"


    - name: Deployment Failed - Attempting Rollback
      command: kubectl rollout undo deployment/{{ app_name }} -n {{ namespace_name }}
      ignore_errors: true

    - name: Get Pod status
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{namespace_name}}"
      register: pod_info
      retries: 3
      delay: 3
      until: >
        pod_info.resources | length > 0 and
        (
        pod_info.resources 
        | selectattr( 'status.phase' , 'equalto', 'pending')
        | list
        | length
        ) == 0

    - name: Show pod status
      debug:
        msg: "{{ item.metadata.name }} | {{ item.status.phase }} | {{ item.status.containerStatuses[0].state.waiting.reason | default('Running') }}"
      loop: "{{ pod_info.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"

    - name: Stop Execution After Failed Deployment
      fail:
        msg: "Deployment of {{ app_name }} failed after retries. Rollback attempted."

  always:
    - name: Deployment Summary
      debug:
        msg: "Deployment status for {{ app_name }}: {{ deployment_status | default('UNKNOWN') }}"